def get_analytics_explanations():
    return {
        "cards": {
            "total_records": _item(
                "Registros",
                "Quantidade de entregas/notas dentro dos filtros aplicados.",
                "Mostra o tamanho da amostra analisada. Quanto menor o recorte, mais cuidado na interpretação.",
                "Use para saber se a análise tem volume suficiente para sustentar uma decisão.",
                "Conta tudo que ficou dentro dos filtros atuais.",
            ),
            "delivered_records": _item(
                "Entregues",
                "Quantidade já concluída dentro do recorte filtrado.",
                "Considera como entregue todo registro cujo status indique entrega finalizada.",
                "Use para medir o quanto do volume filtrado já saiu da fila operacional.",
                "Quanto mais próximo do total de registros, menor o backlog.",
            ),
            "pending_records": _item(
                "Pendentes",
                "Volume que ainda não aparece como entregue.",
                "É a diferença entre o total filtrado e o volume entregue.",
                "Use para enxergar acúmulo de trabalho e possível risco de atraso futuro.",
                "Pendentes = registros totais menos entregues.",
            ),
            "total_invoice_value": _item(
                "Valor total NF",
                "Valor financeiro total das notas dentro dos filtros.",
                "Soma o valor das notas fiscais do recorte atual.",
                "Use para entender o tamanho financeiro da operação analisada.",
                "Quanto maior o valor, maior o impacto financeiro do recorte.",
            ),
            "delayed_invoice_value": _item(
                "Valor NF em atraso",
                "Valor financeiro ligado a registros que tiveram atraso.",
                "Soma as notas com atraso operacional ou atraso de transportadora.",
                "Use para separar atraso pequeno de atraso com impacto financeiro relevante.",
                "Mostra dinheiro parado ou afetado por atraso.",
            ),
            "operational_sla_rate": _item(
                "SLA operacional",
                "Percentual do processo interno concluído dentro do prazo esperado.",
                "Compara os registros dentro do limite operacional contra o total filtrado.",
                "Use para saber se a separação/fluxo interno está cumprindo o combinado.",
                "Quanto maior o percentual, melhor o cumprimento do prazo interno.",
            ),
            "carrier_sla_rate": _item(
                "SLA transportadora",
                "Percentual de entregas feitas pela transportadora dentro do prazo esperado.",
                "Compara registros dentro do limite da transportadora contra o total filtrado.",
                "Use para avaliar desempenho da transportadora sem misturar com a etapa interna.",
                "Quanto maior o percentual, melhor o cumprimento do prazo de transporte.",
            ),
            "operational_lead_time_p90_hours": _item(
                "P90 operacional",
                "Tempo em que a grande maioria dos registros operacionais foi concluída.",
                "Ordena os tempos e mostra um limite que cobre 90% dos casos.",
                "Use para enxergar atrasos escondidos pela média. Se o P90 está alto, há cauda de demora.",
                "90% dos registros ficaram até esse tempo; 10% demoraram mais.",
            ),
            "carrier_lead_time_p90_hours": _item(
                "P90 transportadora",
                "Tempo em que a grande maioria das entregas da transportadora foi concluída.",
                "Ordena os tempos da transportadora e mostra o limite de 90% dos casos.",
                "Use para identificar se poucos casos muito lentos estão prejudicando a percepção do serviço.",
                "90% das entregas ficaram até esse tempo; 10% demoraram mais.",
            ),
            "average_operational_lead_time_hours": _item(
                "Lead time operacional médio",
                "Tempo médio entre a emissão da nota e a conclusão operacional.",
                "Calcula a média de horas úteis do fluxo interno no recorte atual.",
                "Use para acompanhar se a operação está ficando mais rápida ou mais lenta.",
                "Média baixa indica fluxo mais leve; média alta indica gargalo.",
            ),
            "average_carrier_lead_time_hours": _item(
                "Lead time transportadora médio",
                "Tempo médio da etapa sob responsabilidade da transportadora.",
                "Calcula a média de horas úteis do transporte nos registros filtrados.",
                "Use para avaliar se o problema está no transporte ou antes dele.",
                "Média alta aponta demora recorrente na etapa de entrega.",
            ),
            "operational_late_percentage": _item(
                "Atraso operacional",
                "Percentual de registros que passaram do prazo interno.",
                "Compara os atrasos operacionais contra o total filtrado.",
                "Use para medir o peso real do gargalo interno dentro do recorte.",
                "Quanto maior o percentual, mais o processo interno está rompendo prazo.",
            ),
            "carrier_late_percentage": _item(
                "Atraso transportadora",
                "Percentual de registros que passaram do prazo da transportadora.",
                "Compara os atrasos de transporte contra o total filtrado.",
                "Use para apoiar cobrança, revisão de rota ou análise de capacidade da transportadora.",
                "Quanto maior o percentual, mais a entrega final está rompendo prazo.",
            ),
            "top_critical_route": _item(
                "Ponto crítico",
                "Rota com maior prioridade de atenção no recorte atual.",
                "Combina volume, atrasos, valor financeiro e severidade em horas.",
                "Use como ponto inicial de investigação quando precisar agir rápido.",
                "Não é apenas a maior rota; é a rota com maior impacto combinado.",
            ),
            "status_inconsistency_count": _item(
                "Divergências de status",
                "Quantidade de registros com entrega concluída, mas status de carga incoerente.",
                "Procura casos em que a entrega parece finalizada, mas a carga não acompanha o mesmo status.",
                "Use para limpar base, cobrar atualização e evitar leitura errada do dashboard.",
                "Divergência alta indica problema de apontamento ou atualização sistêmica.",
            ),
            "status_inconsistency_percentage": _item(
                "Divergência de status",
                "Percentual da base filtrada com status conflitante.",
                "Divide as divergências pelo total de registros filtrados.",
                "Use para medir se o problema é pontual ou se compromete a confiabilidade da análise.",
                "Percentual baixo tende a ser exceção; percentual alto exige correção de processo.",
            ),
            "peak_billing_day": _item(
                "Maior dia de faturamento",
                "Dia em que entrou o maior volume de notas no recorte.",
                "Agrupa os registros pela data de emissão e encontra o maior volume.",
                "Use para identificar picos de demanda gerados pelo faturamento.",
                "Pico alto pode explicar sobrecarga nos dias seguintes.",
            ),
            "last_3_business_days_records": _item(
                "Faturados nos últimos 3 dias úteis",
                "Volume emitido no fechamento do mês.",
                "Conta notas emitidas nos três últimos dias úteis de cada mês filtrado.",
                "Use para medir a pressão de fechamento sobre a logística.",
                "Volume alto no fim do mês tende a concentrar demanda e risco de atraso.",
            ),
            "last_3_business_days_percentage": _item(
                "Concentração no fim do mês",
                "Parte do volume filtrado que nasceu no fechamento mensal.",
                "Compara o volume dos últimos três dias úteis com o total filtrado.",
                "Use para provar se o fechamento concentra demanda acima do normal.",
                "Quanto maior o percentual, maior a pressão concentrada no fim do mês.",
            ),
            "normal_daily_average_records": _item(
                "Média diária normal",
                "Volume médio diário fora do fechamento do mês.",
                "Calcula a média dos dias que não fazem parte dos últimos três dias úteis.",
                "Use como base de comparação contra o volume do fechamento.",
                "Se o fechamento supera muito essa média, há concentração de demanda.",
            ),
        },
        "charts": {
            "records_by_day": _item(
                "Registros por dia",
                "Volume de notas/entregas criado em cada dia de emissão.",
                "Mostra a entrada diária de demanda para a logística.",
                "Use para localizar picos e entender quando a operação recebeu mais carga.",
                "Barras maiores indicam dias com maior volume de trabalho.",
            ),
            "driver_efficiency_scatter": _item(
                "Eficiência por motorista: volume x lead time",
                "Compara volume atendido, tempo médio e valor financeiro por motorista.",
                "Cada ponto é um motorista: mais à direita é mais volume; mais alto é mais demora.",
                "Use para separar motorista produtivo, motorista sobrecarregado e motorista com atraso recorrente.",
                "O melhor cenário é alto volume com baixo tempo médio.",
            ),
            "critical_routes_ranking": _item(
                "Rotas críticas",
                "Ranking das rotas que mais merecem atenção.",
                "Ordena as rotas pelo impacto combinado de volume, atraso, valor e severidade.",
                "Use para priorizar onde atuar primeiro quando não dá para tratar tudo ao mesmo tempo.",
                "Barras maiores indicam maior prioridade de investigação.",
            ),
            "weekday_bottleneck": _item(
                "Gargalo por dia da semana",
                "Mostra em quais dias da semana os atrasos se concentram.",
                "Compara o percentual de atraso operacional e de transportadora por dia.",
                "Use para ajustar capacidade, escala ou rotina quando o gargalo se repete em dias específicos.",
                "Dia com percentual alto merece análise de causa.",
            ),
            "delay_pareto": _item(
                "Pareto de atrasos por rota",
                "Mostra quais rotas concentram a maior parte dos atrasos.",
                "As barras mostram quantidade de atrasos; a linha mostra o percentual acumulado.",
                "Use para descobrir se poucas rotas explicam boa parte do problema.",
                "Se a linha sobe rápido nas primeiras rotas, a ação deve começar nelas.",
            ),
            "lead_time_distribution": _item(
                "Distribuição de lead time",
                "Mostra em quais faixas de tempo os registros se concentram.",
                "Separa os tempos em grupos, como 0-24h, 24-48h e acima de 96h.",
                "Use para ver se o processo é estável ou se há muitos casos muito demorados.",
                "Quanto mais registros nas faixas altas, maior o risco de atraso recorrente.",
            ),
            "region_lead_time_comparison": _item(
                "Lead time por região",
                "Compara tempo, atraso e criticidade entre regiões.",
                "Agrupa os registros por região quando esse dado está disponível.",
                "Use para identificar áreas geográficas com maior pressão operacional.",
                "Região com tempo e atraso altos deve ser investigada por rota, distância ou capacidade.",
            ),
            "frequency_lead_time_comparison": _item(
                "Lead time por frequência",
                "Compara desempenho por frequência de atendimento.",
                "Agrupa registros pela frequência informada na base.",
                "Use para entender se certas frequências geram mais atraso ou exigem revisão operacional.",
                "Frequência com pior desempenho pode indicar agenda incompatível com a demanda.",
            ),
            "billing_vs_delivery_by_day": _item(
                "Faturados x entregues por dia",
                "Compara a demanda que entrou pelo faturamento com o volume entregue.",
                "Mostra, por dia, quantos registros foram emitidos e quantos foram entregues.",
                "Use para ver se a entrega acompanhou o ritmo do faturamento ou se formou fila.",
                "Quando faturados sobem e entregues não acompanham, há risco de acúmulo.",
            ),
            "delay_by_issue_day": _item(
                "Atrasos por data de faturamento",
                "Mostra se pedidos emitidos em dias específicos geraram mais atraso.",
                "Agrupa os registros pela data de emissão e compara volume com percentuais de atraso.",
                "Use para defender se o gargalo começa na concentração de faturamento.",
                "Picos de emissão com atraso alto indicam sobrecarga na origem da demanda.",
            ),
        },
        "tables": {
            "driver_outliers": _table_item("Motoristas fora da curva", "motorista"),
            "critical_routes": _table_item("Rotas críticas", "pauta/rota"),
            "critical_cities": _table_item("Cidades críticas", "cidade"),
            "critical_regions": _table_item("Regiões críticas", "região"),
            "critical_frequencies": _table_item("Frequências críticas", "frequência"),
            "invoice_outliers": _item(
                "Notas fiscais fora da curva",
                "Lista notas com tempos mais altos dentro do recorte.",
                "Ordena os casos individuais pelos maiores lead times.",
                "Use para investigar exemplos concretos antes de cobrar área, motorista ou transportadora.",
                "As primeiras linhas são os casos mais urgentes para checagem.",
            ),
            "status_inconsistencies": _item(
                "Divergências de status",
                "Lista registros com status de entrega e carga desalinhados.",
                "Mostra os casos individuais que precisam de conferência ou correção.",
                "Use para limpar a base e evitar decisão baseada em status incorreto.",
                "Cada linha é um registro que deve ser verificado.",
            ),
            "commercial_pressure_summary": _item(
                "Resumo de pressão comercial",
                "Compara dias normais com o fechamento do mês.",
                "Mostra volume, valor, atraso e lead time nos dois períodos.",
                "Use para demonstrar se o fechamento comercial aumenta a pressão sobre a logística.",
                "Se o fechamento tem mais volume e mais atraso, há evidência de sobrecarga.",
            ),
        },
        "scores": {
            "criticality_score_v2": _item(
                "Score de criticidade",
                "Nota de prioridade usada para ordenar gargalos.",
                "Combina volume, atraso, valor financeiro e severidade em horas.",
                "Use para decidir onde agir primeiro sem depender de uma única métrica.",
                "Score alto significa maior impacto combinado no recorte filtrado.",
            )
        },
    }


def _table_item(title, group_key):
    return _item(
        title,
        f"Ranking por {group_key} para localizar onde o problema pesa mais.",
        "Compara volume, atrasos, valor financeiro, horas de atraso e score de prioridade.",
        "Use para escolher quais grupos investigar primeiro e para justificar a priorização.",
        "As primeiras linhas têm maior impacto combinado no recorte atual.",
    )


def _item(title, summary, calculation, insight, formula):
    return {
        "title": title,
        "summary": summary,
        "calculation": calculation,
        "insight": insight,
        "formula": formula,
    }
