def get_analytics_explanations():
    return {
        "cards": {
            "total_records": _item(
                "Registros",
                "Total de registros filtrados no banco.",
                "Conta as linhas de LeadTimeRecord que passam pelos filtros aplicados.",
                "Mostra o tamanho da base analisada no recorte atual.",
                "Registros = count(LeadTimeRecord filtrados)",
            ),
            "delivered_records": _item(
                "Entregues",
                "Quantidade de registros com status de entrega concluído.",
                "Conta registros em que o status de entrega contém 'entreg', sem diferenciar maiúsculas.",
                "Indica o volume já concluído dentro do recorte filtrado.",
                "Entregues = count(status de entrega contém 'entreg')",
            ),
            "total_invoice_value": _item(
                "Valor total NF",
                "Soma do valor financeiro das notas filtradas.",
                "Soma o valor das notas fiscais dos registros filtrados.",
                "Ajuda a dimensionar o impacto financeiro do recorte analisado.",
                "Valor total NF = soma(invoice_value)",
            ),
            "delayed_invoice_value": _item(
                "Valor NF em atraso",
                "Soma do valor financeiro de registros com atraso operacional ou transportadora.",
                "Soma o valor das notas fiscais quando há atraso operacional ou atraso de transportadora.",
                "Mostra quanto valor financeiro está associado a atrasos.",
                "Valor NF em atraso = soma(invoice_value dos registros atrasados)",
            ),
            "operational_sla_rate": _item(
                "SLA operacional",
                "Percentual de entregas dentro do limite operacional de 48h úteis.",
                "Conta todos os registros filtrados e subtrai os registros com atraso operacional.",
                "Mostra se a operação interna está cumprindo o prazo esperado.",
                "SLA operacional = ((Registros totais - Atrasos operacionais) / Registros totais) x 100",
            ),
            "carrier_sla_rate": _item(
                "SLA transportadora",
                "Percentual de entregas dentro do limite da transportadora de 24h úteis.",
                "Conta todos os registros filtrados e subtrai os registros com atraso de transportadora.",
                "Mostra se a etapa de transporte está cumprindo o prazo esperado.",
                "SLA transportadora = ((Registros totais - Atrasos transportadora) / Registros totais) x 100",
            ),
            "operational_lead_time_p90_hours": _item(
                "P90 operacional",
                "Tempo abaixo do qual estão 90% dos lead times operacionais.",
                "Ordena os lead times operacionais e seleciona o percentil 90.",
                "Mostra a cauda do processo sem depender apenas da média.",
                "P90 = valor na posição ceil(0,90 x total)",
            ),
            "carrier_lead_time_p90_hours": _item(
                "P90 transportadora",
                "Tempo abaixo do qual estão 90% dos lead times da transportadora.",
                "Ordena os lead times da transportadora e seleciona o percentil 90.",
                "Mostra a cauda da etapa de transporte.",
                "P90 = valor na posição ceil(0,90 x total)",
            ),
            "average_operational_lead_time_hours": _item(
                "Lead time operacional médio",
                "Média de horas úteis da emissão da NF até a entrega.",
                "Calcula a média de lead time operacional dos registros filtrados.",
                "Indica o tempo médio do fluxo completo da operação.",
                "Média operacional = soma(LT operacional) / total com LT operacional",
            ),
            "average_carrier_lead_time_hours": _item(
                "Lead time transportadora médio",
                "Média de horas úteis do carregamento até a entrega.",
                "Calcula a média de lead time da transportadora dos registros filtrados.",
                "Indica o tempo médio sob responsabilidade da transportadora.",
                "Média transportadora = soma(LT transportadora) / total com LT transportadora",
            ),
            "operational_late_percentage": _item(
                "Atraso operacional",
                "Percentual de registros acima de 48h úteis no ciclo operacional.",
                "Divide registros com is_operational_late pelo total filtrado.",
                "Mostra a fatia do recorte que rompeu o alvo operacional.",
                "Atraso operacional = (Atrasos operacionais / Registros totais) x 100",
            ),
            "carrier_late_percentage": _item(
                "Atraso transportadora",
                "Percentual de registros acima de 24h úteis na etapa da transportadora.",
                "Divide registros com is_carrier_late pelo total filtrado.",
                "Mostra a fatia do recorte que rompeu o alvo da transportadora.",
                "Atraso transportadora = (Atrasos transportadora / Registros totais) x 100",
            ),
            "top_critical_route": _item(
                "Ponto crítico",
                "Rota com maior score de criticidade no recorte filtrado.",
                "Ordena rotas pelo score de criticidade v2 e seleciona a primeira.",
                "Aponta onde a ação gerencial deve começar.",
                "Ponto crítico = maior score de criticidade por rota",
            ),
            "pending_records": _item(
                "Pendentes",
                "Registros filtrados que ainda não aparecem como entregues.",
                "Subtrai entregues do total de registros filtrados.",
                "Ajuda a medir backlog operacional no recorte atual.",
                "Pendentes = Registros totais - Entregues",
            ),
            "status_inconsistency_count": _item(
                "Divergências de status",
                "Registros entregues com status de carga incoerente.",
                "Conta registros em que o status de entrega contém 'entreg' e o status de carga não contém 'entreg' ou está vazio.",
                "Aponta falha de atualização operacional ou inconsistência sistêmica.",
                "Divergências = count(status de entrega contém 'entreg' e status de carga não contém 'entreg')",
            ),
            "status_inconsistency_percentage": _item(
                "Divergência de status",
                "Percentual de registros filtrados com divergência de status.",
                "Divide as divergências de status pelo total filtrado.",
                "Mede a qualidade da atualização de status no recorte analisado.",
                "Divergência = (Divergências / Registros totais) x 100",
            ),
            "peak_billing_day": _item(
                "Maior dia de faturamento",
                "Dia com maior quantidade de notas emitidas no recorte filtrado.",
                "Agrupa os registros pela data de emissão da NF e seleciona o maior volume.",
                "Mostra quando a demanda foi concentrada pelo faturamento.",
                "Maior dia = max(count(registros) por data de emissão)",
            ),
            "last_3_business_days_records": _item(
                "Faturados nos últimos 3 dias úteis",
                "Quantidade de registros emitidos nos últimos 3 dias úteis de cada mês filtrado.",
                "Identifica os últimos 3 dias úteis do mês de cada emissão e soma os registros desse período.",
                "Mostra a pressão de fechamento criada no fim do mês.",
                "Faturados fim do mês = count(registros emitidos nos últimos 3 dias úteis)",
            ),
            "last_3_business_days_percentage": _item(
                "Concentração no fim do mês",
                "Percentual do volume filtrado emitido nos últimos 3 dias úteis.",
                "Divide os registros dos últimos 3 dias úteis pelo total de registros filtrados.",
                "Ajuda a provar se o fechamento concentra demanda acima do normal.",
                "Concentração = (Registros dos últimos 3 dias úteis / Registros totais) x 100",
            ),
            "normal_daily_average_records": _item(
                "Média diária normal",
                "Média de registros emitidos fora dos últimos 3 dias úteis.",
                "Soma os registros do período normal e divide pela quantidade de dias com emissão.",
                "Serve como referência para comparar a pressão do fim do mês.",
                "Média normal = Registros fora do fechamento / Dias com emissão fora do fechamento",
            ),
        },
        "charts": {
            "records_by_day": _item(
                "Registros por dia",
                "Volume diário de registros por data de emissão da NF.",
                "Agrupa registros por data de emissão da NF e conta linhas.",
                "Mostra dias com maior volume operacional.",
                "Registros por dia = count(registros) por invoice_issue_date",
            ),
            "driver_efficiency_scatter": _item(
                "Eficiência por motorista: volume x lead time",
                "Cruza quantidade de entregas com lead time médio por motorista.",
                "Cada ponto representa um motorista; X é volume, Y é LT operacional médio, raio é valor NF.",
                "Identifica motoristas com alto volume e baixo ou alto lead time.",
                "X = registros; Y = média LT operacional; Raio = escala por valor NF",
            ),
            "critical_routes_ranking": _item(
                "Rotas críticas",
                "Ranking de rotas pelo score de criticidade v2.",
                "Ordena rotas pela pontuação relativa de prioridade.",
                "Ajuda a priorizar rotas com maior impacto operacional e financeiro.",
                "Score = ((Volume% x 0,20) + (Atrasos% x 0,30) + (Valor NF% x 0,20) + (Severidade h% x 0,30)) x 100",
            ),
            "weekday_bottleneck": _item(
                "Gargalo por dia da semana",
                "Percentual de atraso por dia da semana.",
                "Agrupa registros pelo dia da semana da emissão e calcula atraso operacional e transportadora.",
                "Mostra padrões semanais de gargalo.",
                "Atraso dia % = (Atrasos no dia / Registros no dia) x 100",
            ),
            "delay_pareto": _item(
                "Pareto de atrasos por rota",
                "Rotas com maior quantidade de atrasos e percentual acumulado.",
                "Ordena rotas por atrasos e calcula o acumulado sobre o total atrasado.",
                "Ajuda a identificar poucas rotas que concentram muitos atrasos.",
                "Acumulado % = (Atrasos acumulados / Total de atrasos) x 100",
            ),
            "lead_time_distribution": _item(
                "Distribuição de lead time",
                "Distribuição dos lead times em faixas de horas.",
                "Classifica lead times operacionais e da transportadora em buckets.",
                "Mostra concentração ou dispersão dos tempos.",
                "Bucket = contagem de registros por faixa de horas",
            ),
            "region_lead_time_comparison": _item(
                "Lead time por região",
                "Compara lead time e atraso por região quando a planilha possui esse campo.",
                "Agrupa registros por região e calcula médias, atrasos e score.",
                "Mostra regiões com maior pressão operacional.",
                "Métricas por região = agregações dos registros com mesma região",
            ),
            "frequency_lead_time_comparison": _item(
                "Lead time por frequência",
                "Compara lead time e atraso por frequência quando a planilha possui esse campo.",
                "Agrupa registros por frequência e calcula médias, atrasos e score.",
                "Mostra frequências de atendimento com maior criticidade.",
                "Métricas por frequência = agregações dos registros com mesma frequência",
            ),
            "billing_vs_delivery_by_day": _item(
                "Faturados x entregues por dia",
                "Compara a demanda criada pelo faturamento com a entrega realizada pela logística.",
                "Conta registros pela data de emissão da NF e entregas pela data de entrega ao cliente.",
                "Mostra se o volume faturado foi concentrado em dias específicos e se a entrega acompanhou o ritmo.",
                "Faturados = count(emissão por dia); Entregues = count(entrega por dia)",
            ),
            "delay_by_issue_day": _item(
                "Atrasos por data de faturamento",
                "Mostra se os pedidos emitidos em dias de pico geraram mais atraso.",
                "Agrupa registros pela data de emissão, conta faturados e calcula atraso operacional e transportadora.",
                "Ajuda a defender se o gargalo começa na concentração de faturamento.",
                "Atraso por emissão = (Atrasos dos registros emitidos no dia / Registros emitidos no dia) x 100",
            ),
        },
        "tables": {
            "driver_outliers": _table_item("Motoristas fora da curva", "driver_name"),
            "critical_routes": _table_item("Rotas críticas", "pauta/rota"),
            "critical_cities": _table_item("Cidades críticas", "cidade"),
            "critical_regions": _table_item("Regiões críticas", "região"),
            "critical_frequencies": _table_item("Frequências críticas", "frequência"),
            "invoice_outliers": _item(
                "Notas fiscais fora da curva",
                "Notas com maiores lead times no recorte filtrado.",
                "Ordena registros por LT operacional e LT transportadora em ordem decrescente.",
                "Ajuda a investigar casos individuais de atraso elevado.",
                "Ranking = order by LT operacional desc, LT transportadora desc",
            ),
            "status_inconsistencies": _item(
                "Divergências de status",
                "Registros entregues com status de carga incoerente.",
                "Lista os registros divergentes ordenando por entrega, emissão e NF.",
                "Ajuda a limpar base, cobrar atualização e evitar leitura falsa do processo.",
                "Filtro = status de entrega contém 'entreg' e status de carga não contém 'entreg'",
            ),
            "commercial_pressure_summary": _item(
                "Resumo de pressão comercial",
                "Compara período normal com os últimos 3 dias úteis do mês.",
                "Separa registros pela data de emissão da NF e compara volume, valor, atrasos, lead time e severidade.",
                "Ajuda a demonstrar se o fechamento comercial cria sobrecarga logística.",
                "Comparação = métricas do período normal versus últimos 3 dias úteis",
            ),
        },
        "scores": {
            "criticality_score_v2": _item(
                "Score de criticidade",
                "Pontuação relativa usada para priorizar rotas, motoristas, cidades, regiões ou frequências.",
                "Combina participação em volume, atrasos, valor financeiro e severidade total de atraso em horas.",
                "Ajuda a priorizar onde agir primeiro sem olhar apenas quantidade de atrasos.",
                "Score = ((Volume% x 0,20) + (Atrasos% x 0,30) + (Valor NF% x 0,20) + (Severidade h% x 0,30)) x 100",
            )
        },
    }


def _table_item(title, group_key):
    return _item(
        title,
        "Ranking investigativo por criticidade.",
        f"Agrupa registros por {group_key}, calcula volume, atrasos, valor NF, severidade e score.",
        "Ajuda a localizar prioridades gerenciais no recorte filtrado.",
        "Score = ((Volume% x 0,20) + (Atrasos% x 0,30) + (Valor NF% x 0,20) + (Severidade h% x 0,30)) x 100",
    )


def _item(title, summary, calculation, insight, formula):
    return {
        "title": title,
        "summary": summary,
        "calculation": calculation,
        "insight": insight,
        "formula": formula,
    }
