# Generated by Django 5.2.15 on 2026-06-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mode', models.CharField(choices=[('local', 'Local'), ('sftp', 'SFTP')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('sheet_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('success', 'Sucesso'), ('error', 'Erro'), ('duplicated', 'Duplicado'), ('file_not_found', 'Arquivo não encontrado'), ('validation_error', 'Erro de validação')], db_index=True, default='processing', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('technical_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source_mode'], name='imports_batch_source_idx'), models.Index(fields=['started_at'], name='imports_batch_started_idx'), models.Index(fields=['file_hash', 'status'], name='imports_batch_hash_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('file_hash',), name='unique_successful_import_batch_hash')],
            },
        ),
        migrations.CreateModel(
            name='LeadTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('business_unit', models.CharField(db_index=True, max_length=80)),
                ('map_date', models.DateField()),
                ('map_number', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=150)),
                ('route', models.CharField(db_index=True, max_length=30)),
                ('delivery_points', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=14)),
                ('map_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('driver_code', models.CharField(blank=True, max_length=30)),
                ('driver_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('checker_code', models.CharField(blank=True, max_length=30)),
                ('checker_name', models.CharField(blank=True, max_length=150)),
                ('load_status_description', models.CharField(max_length=80)),
                ('load_date', models.DateField(db_index=True)),
                ('invoice_number', models.CharField(max_length=30)),
                ('invoice_series', models.CharField(max_length=20)),
                ('invoice_issue_date', models.DateField(db_index=True)),
                ('bordero_number', models.CharField(max_length=30)),
                ('customer_code', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_status', models.CharField(max_length=50)),
                ('cargo_status', models.CharField(db_index=True, max_length=50)),
                ('auxiliary_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(db_index=True, max_length=50)),
                ('customer_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('customer_delivery_time', models.TimeField(blank=True, null=True)),
                ('customer_delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('exported_to', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('seller_code', models.CharField(max_length=30)),
                ('team_code', models.CharField(max_length=30)),
                ('operational_lead_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrier_lead_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_operational_late', models.BooleanField(default=False)),
                ('is_carrier_late', models.BooleanField(default=False)),
                ('business_days_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_time_records', to='imports.importbatch')),
            ],
            options={
                'ordering': ['invoice_issue_date', 'invoice_number', 'id'],
                'indexes': [models.Index(fields=['import_batch'], name='imports_record_batch_idx'), models.Index(fields=['invoice_issue_date', 'driver_name'], name='imp_rec_issue_driver_idx'), models.Index(fields=['customer_delivery_date', 'driver_name'], name='imp_rec_delivery_driver_idx'), models.Index(fields=['invoice_number', 'invoice_series'], name='imports_record_invoice_idx'), models.Index(fields=['business_unit', 'invoice_issue_date'], name='imports_record_unit_issue_idx')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'row_number'), name='unique_lead_time_record_batch_row')],
            },
        ),
    ]
