# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadtimerecord",
            name="frequency",
            field=models.CharField(blank=True, db_index=True, default="", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leadtimerecord",
            name="region",
            field=models.CharField(blank=True, db_index=True, default="", max_length=80),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="leadtimerecord",
            index=models.Index(fields=["region"], name="imports_record_region_idx"),
        ),
        migrations.AddIndex(
            model_name="leadtimerecord",
            index=models.Index(fields=["frequency"], name="imports_record_freq_idx"),
        ),
    ]
